### PR TITLE
Updated bot-lax-adaptor to: chore: update project maintainers (#717)

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run https://alfred.elifesciences.org/job/dependencies-lax-update-bot-lax-adaptor/429/display/redirect which resulted in this pull request.

### CODE REVIEW

**Comment by lsh-0** [comment]
@gnott , when you merge these automatic PRs could you close off any older ones while you're at it? cheers

**Comment by gnott** [comment]
Do you mean to delete the branch perhaps? I know I've not been doing that, I will do so.

**Comment by lsh-0** [comment]
I don't mind the branches hanging around tbh ;) just the outstanding PRs can be a little confusing if a newer one has been merged in and an older one exists with conflicts.

**Comment by gnott** [comment]
I usually close older ones but I may have missed this one. I'll keep an eye out when I do merge the PRs to keep it as clean as possible.

**Pull request closed without merging**
