### PR TITLE
Feat python3

### PR DESCRIPTION
**Pull request by lsh-0**
Upgraded Lax to Python3

No massive changes, lots of little ones. Biggest problems were things that were once strings that are now bytes, things that were greedy are now lazy.

I had to upgrade our dependency on rfc3339, so it now points at my fork of it. this means a dependency on mercurial, but all of our machines should have a copy of this. the author has a PR but it doesn't look like he's given the project any love in the last 5 years. I may need to re-publish on Pypi as something else.

### CODE REVIEW

**Comment by lsh-0** [comment]
the `python.sls` in `builder-base-formula` needs updating with python3 deps (python3-dev) and I should probably ensure the latest version of python3 is installed

**Comment by giorgiosironi** [comment]
Given upgrading to Python 2.7.12 made all the virtualenvs out-of-date and `python.sls` is used by many different projects, I think we need a separate `python3.sls` that can be phased in substituting `python.sls` one project at a time.

**Comment by lsh-0** [comment]
precisely my thoughts, too. and right now, only Lax would need python3 deps, so no need to burden any other project

**Comment by lsh-0** [comment]
you might be interested in this one @giorgiosironi : https://github.com/elifesciences/lax/pull/70/commits/5457ed9706179dda22bb87b339c4189f3f9ba08d

**Comment by lsh-0** [comment]
I killed the last test on lax--ci after 47mins
I had noticed it took a little while longer at home, but not that long.
Running it from bash to see if there is some prompt or something causing it to hang

**Comment by lsh-0** [comment]
it's using just less than 300MB ram
there is 4+GB disk available

**Comment by lsh-0** [comment]
rfc3339 has had my changes merged, but I'm still waiting on a release:
https://bitbucket.org/henry/rfc3339/pull-requests/1/minor-tweaks-to-make-python3-compatible/diff

**Comment by lsh-0** [comment]
tests complete locally in 6mins with the current test runner (coverage)

**Comment by lsh-0** [comment]
article is a bit old, but may hold the key to the concurrency issue we witnessed today when Green was using more than one thread:
https://www.caktusgroup.com/blog/2009/05/26/explicit-table-locking-with-postgresql-and-django/

**Comment by lsh-0** [comment]
hey hey! we actually got a pass: https://ci--alfred.elifesciences.org/job/pull-requests-projects/job/lax/job/PR-70/8/console

I can now stop working on this for tonight :|

**Comment by lsh-0** [comment]
http://uwsgi-docs.readthedocs.io/en/latest/Python.html#python-3

"One major change is that applications are required to respond only with bytes instances, not (Unicode) strings, back to the WSGI stack."

this would explain why the test client was inexplicably returning byte responses :)

**Comment by lsh-0** [comment]
`/var/log/uwsgi-lax`:

```
*** Starting uWSGI 2.0.13.1 (64bit) on [Tue Jan 17 22:38:11 2017] ***
compiled with version: 4.8.4 on 03 August 2016 14:55:45
os: Linux-3.13.0-101-generic #148-Ubuntu SMP Thu Oct 20 22:08:32 UTC 2016
nodename: ci--lax.elifesciences.org
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
setgid() to 33
setuid() to 33
chdir() to /srv/lax/src/
your processes number limit is 15922
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /tmp/lax-uwsgi.sock fd 3
Python version: 2.7.12 (default, Jul 18 2016, 15:07:05)  [GCC 4.8.4]
Set PythonHome to /srv/lax/venv/
ImportError: No module named site
VACUUM: unix socket /tmp/lax-uwsgi.sock removed.
```

it seems to be using Python 2.7: `Python version: 2.7.12 (default, Jul 18 2016, 15:07:05)  [GCC 4.8.4]`

**Comment by lsh-0** [comment]
alright, I've figured it out: the version of uwsgi installed is for python2.

what I can do is have lax install the version of uwsgi that is right for it in it's virtualenv and then change the upstart script to:

`exec /srv/lax/venv/bin/newrelic-admin run-program /srv/lax/venv/bin/uwsgi --enable-threads --die-on-term --ini /srv/lax/uwsgi.ini`

**Comment by giorgiosironi** [comment]
Agreed, Lax shipping its own uwsgi. Nevertheless this has to be done both for `develop` and for this branch for the formula to seamlessly work during the migration.

**Comment by lsh-0** [comment]
of course. I'll update the formula and develop and test locally first

**Comment by lsh-0** [comment]
building again after formula update: https://ci--alfred.elifesciences.org/job/pull-requests-projects/job/lax/view/Pull%20Requests/job/PR-70/11/console

**Comment by lsh-0** [comment]
that last link wasn't too helpful. lax has been running on the `venv` version of uwsgi for a bit now:
https://github.com/elifesciences/lax-formula/blob/master/salt/lax/config/etc-init-uwsgi-lax.conf#L9

merging this.

**Pull request merged**
