### PR TITLE
added more fragments to the article snippet

### PR DESCRIPTION
**Pull request by lsh-0**
getting some annoying errors locally I can't pin down. opening PR to see if they can be replicated remotely.

update: can't replicate it with sqlite. I think it's just  psql + green's multithreading

### CODE REVIEW

**Comment by giorgiosironi** [comment]
I think that originally only a subset of `image` was appearing in the snippet (some subfields) but this has been simplified now and there should be only one image for an article.

**Comment by lsh-0** [comment]
um - I think I can avoid that. if I can't, I'll do a backfill today

**Comment by lsh-0** [comment]
yeah, a `./manage.sh revalidate` should do the trick.

**Comment by lsh-0** [comment]
> I think that originally only a subset of image was appearing in the snippet (some subfields) 
> but this has been simplified now and there should be only one image for an article.

I actually encountered this trying to figure out how I managed to make an article invalid in the admin the other day -  the `image` field has become more complex. before it was just a single `uri` type field, now it's a sub-struct with `uri` within it and a lot of other fields. I was using an old database dump and the `image` field with a single value now failed to validate.

**Pull request merged**
