### PR TITLE
Updated bot-lax-adaptor to: Merge pull request #397 from elifesciences/update_elife_tools/70

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run https://alfred.elifesciences.org/job/dependencies-lax-update-bot-lax-adaptor/201/display/redirect which resulted in this pull request.

### CODE REVIEW

**Comment by gnott** [comment]
If the tests pass here, is it ok to deploy? I'm not sure if it includes other features you do not want yet. This includes a parser update to figure attributions.

**Comment by giorgiosironi** [comment]
Personally I would always want the latest version, if there is a feature that has to be disabled for the time being it can use a feature flag (environment variable or configuration setting for example). Currently however Lax is broken due to https://github.com/elifesciences/lax/pull/332 so I'll revert that to keep the option to deploy open.

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/lax/pull/336 should reopen the pipeline.

**Comment by gnott** [comment]
Thanks @giorgiosironi if all is green, I will merge and give this a go.

**Pull request merged**
