### PR TITLE
removes 'abstract' from snippet creation

### PR DESCRIPTION
**Pull request by lsh-0**
* removes 'abstract' from the snippet creation

- [x] add test to ensure 'abstract' isn't present in response or in database

### CODE REVIEW

**Comment by lsh-0** [comment]
*wow*, these tests are **slow**

**Comment by lsh-0** [comment]
the fact that it passes without errors means I have nothing testing the expected output of an article listing page /facepalm

**Comment by gnott** [comment]
I ran tests for lax for the first time a couple weeks ago and I thought it was just me for why the tests seemed slow, not having installed or configured it properly. They were running for maybe fifteen minutes?

**Comment by lsh-0** [comment]
That figure sounds about right.

Some time in the past I switched the test runner from Green to pytest and I suspect it was Green running the tests in parallel and pytest running them serially.

**Comment by lsh-0** [comment]
here we go. I fully expect some end2end tests to fail

**Comment by lsh-0** [comment]
huh no errors. well, good.

**Pull request merged**
