### PR TITLE
Updated bot-lax-adaptor to: Fix deprecation warnings (#929)

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run https://alfred.elifesciences.org/job/dependencies-lax-update-bot-lax-adaptor/619/display/redirect which resulted in this pull request.

### CODE REVIEW

**Comment by gnott** [comment]
This is a result of `bot-lax-adaptor` refactoring, I assume this PR is with you to merge @lsh-0 when it is a good time?

**Comment by lsh-0** [comment]
thanks for the reminder, @gnott , I'll merge today

**Comment by gnott** [comment]
I had a quick peek, and end2end tests may not be passing. In the bot instance there's a message in `/opt/elife-bot/worker.log` which is probably related,

```
"message": "lax failed attempting to handle our request: failed to parse response from lax, expecting json, got error 'Expecting value: line 1 column 1 (char 0)' from stdout 'NEWRELIC: 2023-03-08 01:14:58 (4577) - New Relic could not start because the newrelic-admin script was called from a Python installation that is different from the Python installation that is currently running.
```

**Comment by lsh-0** [comment]
Problem in end2end:

```json
{"asctime": "2023-03-08 01:04:54,853", "filename": "adaptor.py", "funcName": "mkresponse", "levelname": "ERROR", "lineno": 212, "module": "adaptor", "message": "error response", "name": "__main__", "pathname": "src/adaptor.py", "status": "error", "id": "1973564647454015893", "token": "eyJydW4iOiAiNTkyNTg5YzItZWExOC00ZDNjLWE1ZWMtOTljOWUwYWVhZTRhIiwgInZlcnNpb24i\nOiAiMSIsICJleHBhbmRlZF9mb2xkZXIiOiAiMTk3MzU2NDY0NzQ1NDAxNTg5My4xLzU5MjU4OWMy\nLWVhMTgtNGQzYy1hNWVjLTk5YzllMGFlYWU0YSIsICJzdGF0dXMiOiAidm9yIiwgImZvcmNlIjog\nZmFsc2UsICJydW5fdHlwZSI6ICJpbml0aWFsLWFydGljbGUifQ==\n", "datetime": "2023-03-08T01:04:54.853845", "requested-action": "ingest", "status-message": "lax failed attempting to handle our request: failed to parse response from lax, expecting json, got error 'Expecting value: line 1 column 1 (char 0)' from stdout 'NEWRELIC: 2023-03-08 01:04:53 (4771) - New Relic could not start because the newrelic-admin script was called from a Python installation that is different from the Python installation that is currently running. To fix this problem, call the newrelic-admin script from the Python installation that is currently running (details below).\\n\\nnewrelic-admin Python directory: \\'/opt/bot-lax-adaptor/venv\\'\\ncurrent Python directory: \\'/srv/lax/venv\\'\\nnewrelic-admin Python version: \\'3.8\\'\\ncurrent Python version: \\'3.8\\'\\n{\"status\": \"ingested\", \"id\": 1973564647454015893, \"datetime\": \"2023-03-08T01:04:54Z\", \"dry-run\": false, \"force\": false, \"message\": null}\\n'"}
```

The upgraded NewRelicAgent library is emitting this on stdout, messing with json parsing:

```
newrelic-admin Python directory: '/opt/bot-lax-adaptor/venv'
current Python directory: '/srv/lax/venv'
newrelic-admin Python version: '3.8'
current Python version: '3.8'
{"status": "ingested", "id": 1973564647454015893, "datetime": "2023-03-08T01:04:54Z", "dry-run": false, "force": false, "message": null}
```

grr. I'm investigating

**Comment by lsh-0** [comment]
Might have something to do with this:
https://github.com/newrelic/newrelic-python-agent/issues/511

**Comment by lsh-0** [comment]
This should fix it for now: https://github.com/elifesciences/lax-formula/pull/63

**Comment by lsh-0** [comment]
I think long term a better fix would be updating the api-raml and allowing POSTing the JSON to lax

**Comment by gnott** [comment]
Instead of using the SQS queue to send messages from `elife-bot`?

**Comment by lsh-0** [comment]
the SQS stuff is fine, the problem is the bot-lax listener is talking to lax by executing a script and reading the response on stdout, expecting it to be json. In this case, because it's wrapped by NewRelic and NewRelic is complaining on stdout (instead of stderr or writing to a log), the response (above) can't be parsed as json and bot-lax assumes the request failed. The message goes back on the queue and is retried a little while later with the same error. It will eventually timeout.

If the bot-lax listener instead received the SQS message and then POSTed it to lax I could ensure nothing else is writing to the POST response body.

**Comment by lsh-0** [comment]
it's looking better now: https://alfred.elifesciences.org/job/test-lax/1132/

Just an FYI, I have some elife-dashboard work to deploy after this that might see some failures in end2end as well, sorry if I'm interrupting your workflow. Let me know if you need me to get any builds passing that might be blocked by all this.

**Comment by gnott** [comment]
No problems here, I may not even need to deploy anything this week, I'm tinkering on some not-ready-to-merge enhancements.

**Pull request merged**
