### PR TITLE
Updated bot-lax-adaptor to: Merge pull request #124 from elifesciences/feature-elifetools-update

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run http://ci--alfred.elifesciences.org/job/dependencies-lax-update-bot-lax-adaptor/13/ which resulted in this pull request.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Merged the previous one so this conflicts... will wait for the next update.

**Comment by thewilkybarkid** [comment]
This change requires a rebuild of all articles (changes the most common reference type). Can we get it in manually and I'll update Journal to support the change at the same time.

**Comment by giorgiosironi** [comment]
Ok, I'll open a new PR.

**Comment by giorgiosironi** [comment]
The problem is we can only rebuild for published articles, we have no way of doing so for unpublished articles at the moment.

**Comment by giorgiosironi** [comment]
A way that comes to mind is for Lax to store the XML URL of each article version, so that it can be asked about it by the bot-lax-adaptor when doing the rebuild (rather than only using the XML of published articles from elife-article-xml).

**Pull request closed without merging**
