### PR TITLE
Updated bot-lax-adaptor to: Merge pull request #126 from elifesciences/feat-backfill-unpublished

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run http://ci--alfred.elifesciences.org/job/dependencies-lax-update-bot-lax-adaptor/21/ which resulted in this pull request.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
For some reason the app.cfg file requires by the new version of the bot-lax-adaptor is empty in end2end, which broke the build:
```
elife@end2end--lax:/opt/bot-lax-adaptor$ ls -l app.cfg                               │
-rw-r--r-- 1 elife root 0 Mar  6 04:06 app.cfg  
```
Investigating.

**Comment by giorgiosironi** [comment]
At a first glance the formula seems alright, but the build said:
```
          ID: bot-lax-adaptor-config
    Function: file.managed
        Name: /opt/bot-lax-adaptor/app.cfg
      Result: True
     Comment: Empty file
     Started: 04:06:53.037926
    Duration: 1.625 ms
     Changes:   
              ----------
              new:
                  file /opt/bot-lax-adaptor/app.cfg created
              user:
                  elife
```
Notice `Empty file`

**Comment by giorgiosironi** [comment]
Thank you Salt for ignoring syntax errors: https://github.com/elifesciences/lax-formula/commit/0c9643ab6d6de4f733c4665136b79ad691e6fa2c

**Comment by giorgiosironi** [comment]
Also https://github.com/elifesciences/bot-lax-adaptor/commit/a6dc02316bd7ed5ac88e76879d052579ce6e5d2b which makes for two different problems that would have stopped production caught in testing, big success.

**Comment by lsh-0** [comment]
nice catch. I quickly checked `bot-lax-listener.sh` but didn't see any mention of `instance` so stopped looking. it just wraps the hidden file apparently.

**Pull request merged**
