### PR TITLE
Updated bot-lax-adaptor to: Merge pull request #463 from elifesciences/iiif_prod_hostname

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run https://alfred.elifesciences.org/job/dependencies-lax-update-bot-lax-adaptor/241/display/redirect which resulted in this pull request.

### CODE REVIEW

**Comment by lsh-0** [comment]
I've really arsed this up. Reverting

**Comment by lsh-0** [comment]
giving up for the day before I break everything

**Comment by giorgiosironi** [comment]
Usually it suffices to merge the most recent pull request titled `Update bot-lax-adaptor to ...` while the other ones can be closed as obsolete. If a previous one has been merged after this one has been opened, there will be a conflict so better to close it down and do a new run of https://alfred.elifesciences.org/job/dependencies-lax-update-bot-lax-adaptor/

**Comment by giorgiosironi** [comment]
Closing in favor of a new PR that should be opened by https://alfred.elifesciences.org/job/dependencies-lax-update-bot-lax-adaptor/242/

**Comment by lsh-0** [comment]
I was quickly coming to that conclusion actually ;) thank you for spelling it out to me though.

**Pull request closed without merging**
