### PR TITLE
test scripts shifted to use .test-green.sh over .test.sh

### PR DESCRIPTION
**Pull request by lsh-0**
looks like green is counting fewer files than the coverage test runner and is reporting a 75% pass rather than coverage's own 88%

### CODE REVIEW

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/lax/blob/54a492e8a68003e2fdcaf8aa7a5d3827329767eb/src/core/settings.py#L134 seems to say the `junit.xml` file for test results is produced by Django no matter what the runner is, so it should still be there?

**Comment by giorgiosironi** [comment]
If you run into unsolvable problems, another runner we use for parallelization is pytest with the https://pypi.python.org/pypi/pytest-xdist extension. Don't know how it works with the coverage as in end2end tests (where it is used) it's meaningless to measure.

**Comment by lsh-0** [comment]
> seems to say the junit.xml file for test results is produced by Django no matter what the runner is, so it should still be there?

yes, I thought I may have removed it years ago when you started. I can see the `./build/junit.xml` file now. just look at all that wonderful timing data ...

**Comment by giorgiosironi** [comment]
```
LAX_MULTIPROCESSING=1 ./src/manage.py test publisher.tests.test_utils
```
did produce a `build/junit.xml` file for me locally, but
```
GREEN_CONFIG=.green LAX_MULTIPROCESSING=1 ./src/manage.py test publisher.tests.test_utils --testrunner=green.djangorunner.DjangoRunner
```
didn't, leaving `build/` empty.

**Pull request closed without merging**
