### PR TITLE
Updated bot-lax-adaptor to: Merge pull request #564 from elifesciences/update_api_raml/190

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run https://alfred.elifesciences.org/job/dependencies-lax-update-bot-lax-adaptor/294/display/redirect which resulted in this pull request.

### CODE REVIEW

**Comment by gnott** [comment]
Has the same RAML release as PR https://github.com/elifesciences/lax/pull/460 so may we don't need to merge this PR - what do you think @lsh-0 ?

**Comment by lsh-0** [comment]
merge this one!

**Comment by gnott** [comment]
Merging!

**Comment by lsh-0** [comment]
cheers, @gnott . This helps me out in that PR you linked

**Pull request merged**
