### PR TITLE
removed support for 'allow invalid' flag

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by lsh-0** [comment]
this build is failing because it depends on changes in a branch of the api-raml project that hasn't been merged yet

**Comment by giorgiosironi** [comment]
The `develop` branch is now failing, probably because of the latest bot-lax-adaptor:
https://ci--alfred.elifesciences.org/job/test-elife-lax/149/console
It may be that this branch is necessary now for the tests to pass, but I'll verify locally first before merging.

**Comment by giorgiosironi** [comment]
But the build shouldn't depend on the bot-lax-adaptor, so it may be something else. Anyway, looking before modifying anything.

**Comment by giorgiosironi** [comment]
This PR is still green.

**Comment by giorgiosironi** [comment]
Merging this into `develop` makes the local build green on Vagrant, so I'll merge it once I am sure the current end2end tests are already green (https://ci--alfred.elifesciences.org/job/test-elife-dashboard/90/console).

**Comment by giorgiosironi** [comment]
Good, we start from green end2end tests, le'ts go with this as planned.

**Pull request merged**
