### PR TITLE
LAX_MULTIPROCESSING var must be set when ingesting articles in parallel

### PR DESCRIPTION
**Pull request by lsh-0**
related to https://github.com/elifesciences/lax/pull/332

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Or, perhaps it shouldn't be trying to use the parallel mode during normal ingests.

**Comment by giorgiosironi** [comment]
Transformed the assertion into a log so that this can be merged without stopping the pipeline.

**Comment by giorgiosironi** [comment]
Long build, `lax--ci` ate all its credits with a couple of builds. Perhaps it should be resized since it's a `t2.small` running a 15-minute test suite.

**Comment by lsh-0** [comment]
I wasn't clear on where bot-lax was calling the ingest script in the formula and failing, so I introduced the error to see if I could get a failed state. gave your  PR a :+1:  

> 15-minute test suite

do we have metrics on which tests are taking the longest? I feel tests shouldn't take more than 10mins.

running tests with green+sqlite is very fast, but it may miss some db field related issues (constraint checks) and running with green+psql introduces weird locking problems.

**Comment by giorgiosironi** [comment]
> do we have metrics on which tests are taking the longest? I feel tests shouldn't take more than 10mins.

https://alfred.elifesciences.org/job/test-lax/lastCompletedBuild/testReport/
Ignore `(root)` as it contains end2end tests which are run in parallel. The 15 minutes figure includes deployment time.

**Comment by lsh-0** [comment]
hmm - definitely room for some optimisation, but it's only just hovering around the 10min goal so I'll leave it for now

**Pull request merged**
