### PR TITLE
Revert "reverts bot-lax pin to generate v5 content"

### PR DESCRIPTION
**Pull request by gnott**
Reverts revert elifesciences/lax#611, should bring the `bot-lax-adaptor` version in use up to the most recent again.

### CODE REVIEW

**Comment by lsh-0** [comment]
cheers, @gnott

**Review by lsh-0 — APPROVED** [review]
looks fine, but obviously hold off for a bit

**Comment by gnott** [comment]
Is added under step four of the five point plan.

**Comment by lsh-0** [comment]
yes, my five point exploding heart technique

download

**Pull request merged**
